version: '3.8'

services:
  app:
    container_name: t02smith-website
    image: t02smith-website
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000